EMS_USER: admin
EMS_SERVER1: 
EMS_PORT1: 30000
EMS_PASSWORD: password1 
JDBC_USER:  
JDBC_USERNAME:  
JDBC_SID: 
JDBC_SERVER:  
JDBC_PORT: 1521
JDBC_PASSWORD: 
oracle_client_location: /apps/oracle/client
min_pool_size: 50
max_pool_size: 500
ConfigValues_XML: ConfigValues.xml.j2
mdm_root_dir: /app
oracle_dir: /apps
JDBC_CONNECTION: 
